### Bibliotecas

In [9]:
!pip install pandasql

Collecting pandasql
  Downloading pandasql-0.7.3.tar.gz (26 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: numpy in c:\users\samuel\anaconda3\lib\site-packages (from pandasql) (1.24.3)
Requirement already satisfied: pandas in c:\users\samuel\anaconda3\lib\site-packages (from pandasql) (2.0.3)
Requirement already satisfied: sqlalchemy in c:\users\samuel\anaconda3\lib\site-packages (from pandasql) (1.4.39)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\samuel\anaconda3\lib\site-packages (from pandas->pandasql) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\samuel\anaconda3\lib\site-packages (from pandas->pandasql) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\samuel\anaconda3\lib\site-packages (from pandas->pandasql) (2023.3)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\samuel\anaconda3\lib\site-packages (from sqlalchemy->pandasql) (2.0.1)
Requirement already satisfied: six>=1.5 in c:\users\samuel\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas->pandasql) (1.16.0)
Building wheels for collected packages: pandasql
  Building wheel for pandasql (setup.py): started
  Building wheel for pandasql (setup.py): finished with status 'done'
  Created wheel for pandasql: filename=pandasql-0.7.3-py3-none-any.whl size=26800 sha256=dbad3c4e6d70b7265b161fddbb80db04e7676970827fbaf723cca73467916dde
  Stored in directory: c:\users\samuel\appdata\local\pip\cache\wheels\68\5d\a5\edc271b998f909801d7956959f699b976cc9896075dc47c153
Successfully built pandasql
Installing collected packages: pandasql
Successfully installed pandasql-0.7.3

In [23]:
import pandas as pd
from pandasql import sqldf

### Carregamento de Dados

In [24]:
categories = pd.read_csv('categories.csv')

In [25]:
categories

   id                     name
0   0        Moda e Acessórios
1   1  Cosméticos e Perfumaria
2   2         Eletrodomésticos
3   3                   Livros
4   4                Celulares
5   5              Informática
6   6         Casa e Decoração
7   7              Eletrônicos
8   8          Esporte e Lazer
9   9       Brinquedos e Games

In [26]:
products = pd.read_csv('products.csv')

In [27]:
products

    id                  name  price  category_id
0    0                Sapato     96            0
1    1                 Bolsa     21            0
2    2                 Calça     75            0
3    3                Camisa     70            0
4    4               Vestido     57            0
5    5               Perfume     29            1
6    6      Creme de Barbear     15            1
7    7            Hidratante     10            1
8    8               Shampoo     15            1
9    9        Protetor Solar     11            1
10  10             Geladeira   1952            2
11  11                 Fogão   1373            2
12  12                    TV   1992            2
13  13      Máquina de Lavar   1826            2
14  14      Máquina de Secar   1774            2
15  15   O Romance Exagerado     46            3
16  16       Suspense Demais     42            3
17  17  Terror Aterrorizante     45            3
18  18   A Comédia Engraçada     20            3
19  19     A História de SQL     23            3
20  20               Ai-Fone   1720            4
21  21           Galáxia R10   2007            4
22  22            Chiai-homi   1152            4
23  23                 Ruaei   2795            4
24  24                Nóquia   2663            4
25  25                 Mouse    144            5
26  26               Teclado     53            5
27  27             Pen-Drive    136            5
28  28            Impressora    186            5
29  29            HD Externo    110            5
30  30              Poltrona    110            6
31  31              Almofada    170            6
32  32               Cadeira    164            6
33  33                  Sofá    111            6
34  34                  Mesa    143            6
35  35            Video-Game    602            7
36  36   Máquina Fotográfica    377            7
37  37              Notebook    493            7
38  38                    PC    385            7
39  39     Secador de Cabelo    580            7
40  40              Chuteira    128            8
41  41          Tornozeleira     61            8
42  42               Raquete     97            8
43  43                  Bola    103            8
44  44               Pebolim     82            8
45  45          Futebol 2020     36            9
46  46                  Iôiô     16            9
47  47                  Peão     32            9
48  48             Bey-Blade     55            9
49  49     Casinha de Boneca     39            9

### Combinando as informações dos dataframes com linguagem SQL

In [31]:
query = """

SELECT
p.id as product_id,
p.name as product_name,
p.price,
c.name as category_name 

FROM products p
JOIN categories c on c.id = p.category_id

"""

In [32]:
resultado = sqldf(query)

In [33]:
resultado

    product_id          product_name  price            category_name
0            0                Sapato     96        Moda e Acessórios
1            1                 Bolsa     21        Moda e Acessórios
2            2                 Calça     75        Moda e Acessórios
3            3                Camisa     70        Moda e Acessórios
4            4               Vestido     57        Moda e Acessórios
5            5               Perfume     29  Cosméticos e Perfumaria
6            6      Creme de Barbear     15  Cosméticos e Perfumaria
7            7            Hidratante     10  Cosméticos e Perfumaria
8            8               Shampoo     15  Cosméticos e Perfumaria
9            9        Protetor Solar     11  Cosméticos e Perfumaria
10          10             Geladeira   1952         Eletrodomésticos
11          11                 Fogão   1373         Eletrodomésticos
12          12                    TV   1992         Eletrodomésticos
13          13      Máquina de Lavar   1826         Eletrodomésticos
14          14      Máquina de Secar   1774         Eletrodomésticos
15          15   O Romance Exagerado     46                   Livros
16          16       Suspense Demais     42                   Livros
17          17  Terror Aterrorizante     45                   Livros
18          18   A Comédia Engraçada     20                   Livros
19          19     A História de SQL     23                   Livros
20          20               Ai-Fone   1720                Celulares
21          21           Galáxia R10   2007                Celulares
22          22            Chiai-homi   1152                Celulares
23          23                 Ruaei   2795                Celulares
24          24                Nóquia   2663                Celulares
25          25                 Mouse    144              Informática
26          26               Teclado     53              Informática
27          27             Pen-Drive    136              Informática
28          28            Impressora    186              Informática
29          29            HD Externo    110              Informática
30          30              Poltrona    110         Casa e Decoração
31          31              Almofada    170         Casa e Decoração
32          32               Cadeira    164         Casa e Decoração
33          33                  Sofá    111         Casa e Decoração
34          34                  Mesa    143         Casa e Decoração
35          35            Video-Game    602              Eletrônicos
36          36   Máquina Fotográfica    377              Eletrônicos
37          37              Notebook    493              Eletrônicos
38          38                    PC    385              Eletrônicos
39          39     Secador de Cabelo    580              Eletrônicos
40          40              Chuteira    128          Esporte e Lazer
41          41          Tornozeleira     61          Esporte e Lazer
42          42               Raquete     97          Esporte e Lazer
43          43                  Bola    103          Esporte e Lazer
44          44               Pebolim     82          Esporte e Lazer
45          45          Futebol 2020     36       Brinquedos e Games
46          46                  Iôiô     16       Brinquedos e Games
47          47                  Peão     32       Brinquedos e Games
48          48             Bey-Blade     55       Brinquedos e Games
49          49     Casinha de Boneca     39       Brinquedos e Games